import { useState } from "react";
import { Link } from "react-router-dom";
import InputField from "../components/ui/InputField";
import GoogleLogo from "../components/ui/GoogleLogo";
import { useAuth } from "../hooks/useAuth";
import "../styles/auth.css";

/* ── Icons ──────────────────────────────────────────────────── */
const UserIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="8" r="4"/>
    <path d="M4 20c0-4 3.6-7 8-7s8 3 8 7"/>
  </svg>
);

const EmailIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
    <rect x="2" y="4" width="20" height="16" rx="3"/>
    <path d="m2 7 10 7 10-7"/>
  </svg>
);

const KeyIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="8" cy="15" r="3"/>
    <path d="M11 15h7V5H8v6"/>
  </svg>
);

const ErrorIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="12" r="10"/>
    <line x1="12" y1="8" x2="12" y2="12"/>
    <line x1="12" y1="16" x2="12.01" y2="16"/>
  </svg>
);

/* ── Terms content ───────────────────────────────────────────── */
const TERMS = [
  ["1. Acceptance",              "By using SUMMIFY, you agree to these Terms & Conditions. If you do not agree, please do not use the application."],
  ["2. Use of Service",          "SUMMIFY is a document summarization tool. You agree to use it only for lawful purposes and not to upload content that violates any applicable laws."],
  ["3. Privacy",                 "We collect minimal data necessary to provide the service. Your uploaded documents are processed in-browser where possible and are not stored on our servers without your consent."],
  ["4. AI-Generated Content",    "Summaries are generated by AI models. Results may not be perfectly accurate. Do not rely solely on summaries for critical decisions."],
  ["5. Intellectual Property",   "You retain ownership of any content you upload. By using SUMMIFY, you grant us a limited license to process your content for the purpose of providing the service."],
  ["6. Limitation of Liability", "SUMMIFY is provided as-is. We are not liable for any damages arising from the use or inability to use the service."],
  ["7. Changes",                 "We reserve the right to update these terms at any time. Continued use of the app after changes constitutes acceptance of the new terms."],
];

/* ── Terms modal ─────────────────────────────────────────────── */
function TermsModal({ onClose }) {
  return (
    <div className="terms-backdrop" onClick={onClose}>
      <div className="terms-sheet" onClick={(e) => e.stopPropagation()}>
        <div className="terms-handle" />
        <h2 className="terms-title">Terms &amp; Conditions</h2>
        {TERMS.map(([title, body]) => (
          <div key={title}>
            <p className="terms-section-title">{title}</p>
            <p className="terms-section-body">{body}</p>
          </div>
        ))}
        <button type="button" className="terms-close-btn" onClick={onClose}>
          Got it
        </button>
      </div>
    </div>
  );
}

/* ── SignUp Page ─────────────────────────────────────────────── */
export default function SignUp() {
  const {
    fields, errors, authError, loading,
    handleChange, handleSignUp, handleGoogle,
  } = useAuth();

  const [agreed,     setAgreed]     = useState(false);
  const [agreeError, setAgreeError] = useState(false);
  const [termsOpen,  setTermsOpen]  = useState(false);

  function handleSubmit(e) {
    e.preventDefault();
    if (!agreed) {
      setAgreeError(true);
      return;
    }
    setAgreeError(false);
    handleSignUp(e);
  }

  return (
    <div className="auth-screen auth-screen--signup">

      <div className="auth-logo-wrap">
        <div className="auth-logo-box">
          <span className="auth-logo-letter">S</span>
        </div>
      </div>

      <h1 className="auth-title auth-title--accent">Sign Up</h1>

      {/* Top-level auth error */}
      {authError && (
        <div className="auth-error-banner">
          <ErrorIcon />
          {authError}
        </div>
      )}

      <form onSubmit={handleSubmit} noValidate className="auth-form">

        <InputField
          id="username"
          type="text"
          placeholder="Username"
          value={fields.username || ""}
          onChange={handleChange}
          error={errors.username}
          icon={<UserIcon />}
        />

        <InputField
          id="email"
          type="email"
          placeholder="Email"
          value={fields.email || ""}
          onChange={handleChange}
          error={errors.email}
          icon={<EmailIcon />}
        />

        <InputField
          id="password"
          type="password"
          placeholder="Password"
          value={fields.password || ""}
          onChange={handleChange}
          error={errors.password}
          icon={<KeyIcon />}
        />

        {/* Terms & Conditions checkbox */}
        <div className="terms-row">
          <input
            type="checkbox"
            id="terms"
            className="terms-checkbox"
            checked={agreed}
            onChange={(e) => {
              setAgreed(e.target.checked);
              setAgreeError(false);
            }}
          />
          <label htmlFor="terms" className="terms-label">
            I agree to the{" "}
            <button
              type="button"
              className="terms-link"
              onClick={() => setTermsOpen(true)}
            >
              Terms &amp; Conditions
            </button>
          </label>
        </div>
        {agreeError && (
          <p className="terms-agree-error">
            You must agree to the Terms &amp; Conditions to continue.
          </p>
        )}

        <button type="submit" className="btn-auth-primary" disabled={loading}>
          {loading ? <span className="btn-spinner" /> : "Sign Up"}
        </button>

        <span className="auth-or">or</span>

        <button type="button" className="btn-google" onClick={handleGoogle} disabled={loading}>
          <GoogleLogo size={24} />
          <span>Continue with Google</span>
        </button>

      </form>

      <p className="auth-switch">
        Already have an Account? <Link to="/sign-in">Sign In</Link>
      </p>

      {termsOpen && <TermsModal onClose={() => setTermsOpen(false)} />}

    </div>
  );
}